# Generated by Django 4.1.1 on 2022-09-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
                ("IsActive", models.BooleanField(default=False)),
            ],
            options={"db_table": "master",},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(default="", max_length=25)),
                ("Mobile", models.CharField(default="", max_length=10)),
                ("BirthDate", models.DateField()),
                (
                    "Gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=5
                    ),
                ),
                ("Country", models.CharField(default="", max_length=15)),
                ("State", models.CharField(default="", max_length=15)),
                ("City", models.CharField(default="", max_length=15)),
                ("Address", models.TextField(default="", max_length=200)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolioApp.master",
                    ),
                ),
            ],
            options={"db_table": "userprofile",},
        ),
    ]
